// <auto-generated />
using System;
using BookinhMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookinhMVC.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20260406130532_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookinhMVC.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("FeatureImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("ArticleId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("BookinhMVC.Models.BacSi", b =>
                {
                    b.Property<int>("MaBacSi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaBacSi"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HinhAnhBacSi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaBacSi");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("BacSis");
                });

            modelBuilder.Entity("BookinhMVC.Models.BenhNhan", b =>
                {
                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("longtext");

                    b.Property<string>("HinhAnhBenhNhan")
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoBaoHiem")
                        .HasColumnType("longtext");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext");

                    b.HasKey("MaBenhNhan");

                    b.ToTable("BenhNhans");
                });

            modelBuilder.Entity("BookinhMVC.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BookinhMVC.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("BookinhMVC.Models.CsKh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CsKhs");
                });

            modelBuilder.Entity("BookinhMVC.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhanXet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaBenhNhan");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("BookinhMVC.Models.GiaoDichThanhToan", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaGiaoDich"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LoaiGiaoDich")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaLich")
                        .HasColumnType("int");

                    b.Property<string>("MaThamChieu")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayGiaoDich")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NguoiXuLy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaGiaoDich");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaLich");

                    b.ToTable("GiaoDichThanhToan");
                });

            modelBuilder.Entity("BookinhMVC.Models.HoSoBenhAn", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaHoSo"));

                    b.Property<string>("ChanDoan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhuongAnDieuTri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaBenhNhan");

                    b.ToTable("HoSoBenhAns");
                });

            modelBuilder.Entity("BookinhMVC.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("BookinhMVC.Models.LichHen", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<bool>("DaThongBao")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrieuChung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaLich");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaBacSi", "NgayGio")
                        .IsUnique();

                    b.ToTable("LichHens");
                });

            modelBuilder.Entity("BookinhMVC.Models.LichLamViec", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time(6)");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ThuTrongTuan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaLich");

                    b.HasIndex("MaBacSi");

                    b.ToTable("LichLamViecs");
                });

            modelBuilder.Entity("BookinhMVC.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("BookinhMVC.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("BookinhMVC.Models.TaiKhoanBenhNhan", b =>
                {
                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("SoDuHienTai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTienChi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTienNap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaBenhNhan");

                    b.ToTable("TaiKhoanBenhNhan");
                });

            modelBuilder.Entity("BookinhMVC.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaXem")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaLichHen")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaThongBao");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("BookinhMVC.Models.Article", b =>
                {
                    b.HasOne("BookinhMVC.Models.NguoiDung", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookinhMVC.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookinhMVC.Models.BacSi", b =>
                {
                    b.HasOne("BookinhMVC.Models.Khoa", "Khoa")
                        .WithMany("BacSis")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookinhMVC.Models.NguoiDung", "NguoiDung")
                        .WithOne("BacSi")
                        .HasForeignKey("BookinhMVC.Models.BacSi", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BookinhMVC.Models.BenhNhan", b =>
                {
                    b.HasOne("BookinhMVC.Models.NguoiDung", "NguoiDung")
                        .WithOne("BenhNhan")
                        .HasForeignKey("BookinhMVC.Models.BenhNhan", "MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BookinhMVC.Models.DanhGia", b =>
                {
                    b.HasOne("BookinhMVC.Models.BacSi", "BacSi")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookinhMVC.Models.BenhNhan", "BenhNhan")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("BookinhMVC.Models.GiaoDichThanhToan", b =>
                {
                    b.HasOne("BookinhMVC.Models.BenhNhan", "BenhNhan")
                        .WithMany("GiaoDichThanhToans")
                        .HasForeignKey("MaBenhNhan")
                        .IsRequired();

                    b.HasOne("BookinhMVC.Models.LichHen", "LichHen")
                        .WithMany()
                        .HasForeignKey("MaLich");

                    b.Navigation("BenhNhan");

                    b.Navigation("LichHen");
                });

            modelBuilder.Entity("BookinhMVC.Models.HoSoBenhAn", b =>
                {
                    b.HasOne("BookinhMVC.Models.BacSi", "BacSi")
                        .WithMany("HoSoBenhAns")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookinhMVC.Models.BenhNhan", "BenhNhan")
                        .WithMany("HoSoBenhAns")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("BookinhMVC.Models.LichHen", b =>
                {
                    b.HasOne("BookinhMVC.Models.BacSi", "BacSi")
                        .WithMany("LichHens")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookinhMVC.Models.BenhNhan", "BenhNhan")
                        .WithMany("LichHens")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("BookinhMVC.Models.LichLamViec", b =>
                {
                    b.HasOne("BookinhMVC.Models.BacSi", "BacSi")
                        .WithMany("LichLamViecs")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacSi");
                });

            modelBuilder.Entity("BookinhMVC.Models.Question", b =>
                {
                    b.HasOne("BookinhMVC.Models.BacSi", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("BookinhMVC.Models.NguoiDung", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookinhMVC.Models.TaiKhoanBenhNhan", b =>
                {
                    b.HasOne("BookinhMVC.Models.BenhNhan", "BenhNhan")
                        .WithOne()
                        .HasForeignKey("BookinhMVC.Models.TaiKhoanBenhNhan", "MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("BookinhMVC.Models.BacSi", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("HoSoBenhAns");

                    b.Navigation("LichHens");

                    b.Navigation("LichLamViecs");
                });

            modelBuilder.Entity("BookinhMVC.Models.BenhNhan", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("GiaoDichThanhToans");

                    b.Navigation("HoSoBenhAns");

                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("BookinhMVC.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("BookinhMVC.Models.Khoa", b =>
                {
                    b.Navigation("BacSis");
                });

            modelBuilder.Entity("BookinhMVC.Models.NguoiDung", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("BacSi")
                        .IsRequired();

                    b.Navigation("BenhNhan")
                        .IsRequired();

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
